# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/titico03/PogExpressionEvaluator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/titico03/PogExpressionEvaluator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/titico03/PogExpressionEvaluator/CMakeFiles /home/titico03/PogExpressionEvaluator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/titico03/PogExpressionEvaluator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named token

# Build rule for target.
token: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 token
.PHONY : token

# fast build rule for target.
token/fast:
	$(MAKE) -f CMakeFiles/token.dir/build.make CMakeFiles/token.dir/build
.PHONY : token/fast

#=============================================================================
# Target rules for targets named METH

# Build rule for target.
METH: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 METH
.PHONY : METH

# fast build rule for target.
METH/fast:
	$(MAKE) -f CMakeFiles/METH.dir/build.make CMakeFiles/METH.dir/build
.PHONY : METH/fast

#=============================================================================
# Target rules for targets named lexicon

# Build rule for target.
lexicon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lexicon
.PHONY : lexicon

# fast build rule for target.
lexicon/fast:
	$(MAKE) -f CMakeFiles/lexicon.dir/build.make CMakeFiles/lexicon.dir/build
.PHONY : lexicon/fast

lexicon/lexicon.o: lexicon/lexicon.cpp.o

.PHONY : lexicon/lexicon.o

# target to build an object file
lexicon/lexicon.cpp.o:
	$(MAKE) -f CMakeFiles/lexicon.dir/build.make CMakeFiles/lexicon.dir/lexicon/lexicon.cpp.o
.PHONY : lexicon/lexicon.cpp.o

lexicon/lexicon.i: lexicon/lexicon.cpp.i

.PHONY : lexicon/lexicon.i

# target to preprocess a source file
lexicon/lexicon.cpp.i:
	$(MAKE) -f CMakeFiles/lexicon.dir/build.make CMakeFiles/lexicon.dir/lexicon/lexicon.cpp.i
.PHONY : lexicon/lexicon.cpp.i

lexicon/lexicon.s: lexicon/lexicon.cpp.s

.PHONY : lexicon/lexicon.s

# target to generate assembly for a file
lexicon/lexicon.cpp.s:
	$(MAKE) -f CMakeFiles/lexicon.dir/build.make CMakeFiles/lexicon.dir/lexicon/lexicon.cpp.s
.PHONY : lexicon/lexicon.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/METH.dir/build.make CMakeFiles/METH.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/METH.dir/build.make CMakeFiles/METH.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/METH.dir/build.make CMakeFiles/METH.dir/main.cpp.s
.PHONY : main.cpp.s

token/token.o: token/token.cpp.o

.PHONY : token/token.o

# target to build an object file
token/token.cpp.o:
	$(MAKE) -f CMakeFiles/token.dir/build.make CMakeFiles/token.dir/token/token.cpp.o
.PHONY : token/token.cpp.o

token/token.i: token/token.cpp.i

.PHONY : token/token.i

# target to preprocess a source file
token/token.cpp.i:
	$(MAKE) -f CMakeFiles/token.dir/build.make CMakeFiles/token.dir/token/token.cpp.i
.PHONY : token/token.cpp.i

token/token.s: token/token.cpp.s

.PHONY : token/token.s

# target to generate assembly for a file
token/token.cpp.s:
	$(MAKE) -f CMakeFiles/token.dir/build.make CMakeFiles/token.dir/token/token.cpp.s
.PHONY : token/token.cpp.s

token/token_record.o: token/token_record.cpp.o

.PHONY : token/token_record.o

# target to build an object file
token/token_record.cpp.o:
	$(MAKE) -f CMakeFiles/token.dir/build.make CMakeFiles/token.dir/token/token_record.cpp.o
.PHONY : token/token_record.cpp.o

token/token_record.i: token/token_record.cpp.i

.PHONY : token/token_record.i

# target to preprocess a source file
token/token_record.cpp.i:
	$(MAKE) -f CMakeFiles/token.dir/build.make CMakeFiles/token.dir/token/token_record.cpp.i
.PHONY : token/token_record.cpp.i

token/token_record.s: token/token_record.cpp.s

.PHONY : token/token_record.s

# target to generate assembly for a file
token/token_record.cpp.s:
	$(MAKE) -f CMakeFiles/token.dir/build.make CMakeFiles/token.dir/token/token_record.cpp.s
.PHONY : token/token_record.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... token"
	@echo "... METH"
	@echo "... lexicon"
	@echo "... lexicon/lexicon.o"
	@echo "... lexicon/lexicon.i"
	@echo "... lexicon/lexicon.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... token/token.o"
	@echo "... token/token.i"
	@echo "... token/token.s"
	@echo "... token/token_record.o"
	@echo "... token/token_record.i"
	@echo "... token/token_record.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

